### ISSUE TITLE
Question - wandering can this be used in the browser?

### ISSUE THREAD

**Issue by contactsamie** [MorganConrad/json-to-graphql-typesystem#2]
Wandering can this be used in the browser and what will be a javascript example of that , i believe its using JSONToGraphQLTS?

**Comment by MorganConrad** [comment]
Never tried it, but it should work.

1. import json-to-graphql-typesystem.js into your browser
2. create a `let js2gql = new  JSONToGraphQLTS()`, 
3. use fetch to get some example JSON data, call `let jsob = response.json()` to convert to an object
4. `js2gql.convert(jsob)`  or `js2sql,cibvertToHash(jsob)`

**Comment by MorganConrad** [comment]
See new file   browser_example.html added in version 0.3.2 for very quick and dirty code.

**Comment by contactsamie** [comment]
@MorganConrad  Thank you so much. it worked
